### ISSUE TITLE
No Compiler found in Linux

### ISSUE THREAD

**Issue by DD-NDD** [LubinKerhuel/MPLAB-Device-Blocks-for-Simulink#1]
![Screenshot from 2019-12-14 14-58-17](https://user-images.githubusercontent.com/31593177/70845520-3c089a80-1e82-11ea-8646-2d3ffd770376.png)
![image](https://user-images.githubusercontent.com/31593177/70845529-678b8500-1e82-11ea-9199-30824b19d87f.png)
I installed xc16 and build success in IDE but in MATLAB simulink, block compiler not detect xc16 compiler.
Thanks your support

**Comment by jorgejorge0203** [comment]
I had the same problem, but when I installed  XC16 compiller in the same folder of matlab it works 
example:
C:/ProgramFiles/Matlab
C:/ProgramFiles/Microchip/XC16

**Comment by LubinKerhuel** [comment]
Linux support added in 2021.
