### ISSUE TITLE
No PWM

### ISSUE THREAD

**Issue by belzebuth974** [LubinKerhuel/MPLAB-Device-Blocks-for-Simulink#2]
Hi, 
when i try for example to make a model with a dpsic 33CH128mp508 there is no pwm of anykind avalaible and  same issue for any dspic33ch.  tested with matlab 2015A and 2020 and still get the message "chip 33CH128MP508 does not have this type of PWM peripheral. pick the correct PWM block type" and that for all of the dspic33CH.

I'm i doing something wrong ?

package is version 3.46.063

thanks

**Comment by LubinKerhuel** [comment]
PWM for that chip is supported. This Issue seems old (use Microchip Matlab dedicated forum which I do monitor more often !). 
Let me know if the issue is still present with current release (3.50.16)
