### ISSUE TITLE
Mailbox config defines v3.47

### ISSUE THREAD

**Issue by Virland-IRZ** [LubinKerhuel/MPLAB-Device-Blocks-for-Simulink#3]
After upgrading the blockset version (v3.46.05 -> v3.47), I ran into a problem: the connection between the main and slave cores via mailboxes disappeared.
After analyzing the generated code, a difference was found - in the new version of the blockset, the defines of the mailbox settings registers are not written.
Instead of the whole config, I got a define:
#pragma config MBXM0 = S2M

but in old version it was:
#pragma config MBXM0 = S2M, MBXM1 = M2S, MBXM2 = M2S, MBXM3 = M2S, MBXM4 = M2S, MBXM5 = M2S, MBXM6 = M2S, MBXM7 = M2S, MBXM8 = M2S, MBXM9 = M2S, MBXM14 = M2S
#pragma config MBXHSA = MBX9, MBXHSB = MBX13
#pragma config MBXHSG = MBX14

P.S. I use the following procedure for generating firmware: I generate MPLAB projects as a consequence of simulink, open them with MPLAB and build the firmware.

**Comment by LubinKerhuel** [comment]
That was fixed. Please give a try with the v3.50.16
